---
mozilla-central:
- when: '0 1 * * *'
  task:
    provisionerId: aws-provisioner-v1
    workerType: gecko-decision
    schedulerId: task-graph-scheduler
    routes:
    priority: normal
    retries: 5
    deadline: "1 day"
    expires: "1 year"
    scopes:
    - docker-worker:cache:level-3-mozilla-central-tc-vcs-public-sources
    payload:
      env:
        GECKO_BASE_REPOSITORY: https://hg.mozilla.org/integration/mozilla-central/
        GECKO_HEAD_REPOSITORY: https://hg.mozilla.org/integration/mozilla-central/
        GECKO_HEAD_REF: {{ revision }}
        GECKO_HEAD_REV: {{ revision }}
      cache:
        level-3-mozilla-central-tc-vcs-public-sources: "/home/worker/.tc-vcs/"
      image: taskcluster/builder:0.5.11
      maxRunTime: 1800
      command:
      - "/bin/bash"
      - "-cx"
      - 'mkdir -p /home/worker/artifacts && checkout-gecko workspace && cd workspace/gecko
        && ./mach taskgraph decision --nightly --project=''mozilla-central''
        --message='' '' --owner=''jolesen@mozilla.com'' --level=''3'' --revision-hash=''{{ revision }}''
        --extend-graph > /home/worker/artifacts/graph.json

    '
    metadata:
      owner: mozilla-taskcluster-maintenance@mozilla.com
      source: https://hg.mozilla.org/integration/mozilla-central/raw-file/{{ revision }}/cron.yml
      name: Initial decision task for mozilla-central nightlies
      description: |
        This is the single most important task as it decides how all other tasks
        get built.
    tags:
      createdForUser: nightly@mozilla.org
    extra:
      treeherder:
        symbol: D

