attributes:
  platform: "macosx64"

task:
  metadata:
      name: '[TC] MacOSX64 {{build-type}}'
      description: 'MacOSX64 {{build-type}}'

  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-macosx64-{{build-type}}-workspace'
    - 'docker-worker:cache:tooltool-cache'
    - 'docker-worker:relengapi-proxy:tooltool.download.internal'
    - 'docker-worker:relengapi-proxy:tooltool.download.public'

  routes:
    - 'index.buildbot.branches.{{project}}.macosx64'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.macosx64'

  workerType: opt-macosx64

  payload:
    image:
      type: 'task-image'
      path: 'public/image.tar'
      taskId: '{{#task_id_for_link}}linux-image{{/task_id_for_link}}'
    cache:
      level-{{level}}-{{project}}-build-macosx64-{{build-type}}-workspace: '/home/worker/workspace'
      tooltool-cache: '/home/worker/tooltool-cache'
    features:
      relengAPIProxy: true
    env:
      MOZHARNESS_SCRIPT: 'mozharness/scripts/fx_desktop_build.py'
      MOZHARNESS_CONFIG: 'builds/releng_base_mac_64_cross_builds.py balrog/production.py'
      MH_BRANCH: {{project}}
      MH_BUILD_POOL: taskcluster
      TOOLTOOL_CACHE: '/home/worker/tooltool-cache'
      # link to the toolchain
      TOOLCHAIN_URL: "http://taskcluster/queue/task/{{#task_id_for_link}}macosx-toolchain{{/task_id_for_link}}/artifacts/private/toolchain.tgz"
    maxRunTime: 36000
    command: ["/bin/bash", "bin/build.sh"]

  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      machine:
        # see https://github.com/mozilla/treeherder/blob/master/ui/js/values.js
        platform: osx-10-7
    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located.
    locations:
      build: 'public/build/target.dmg'
      tests: 'public/build/target.tests.zip'
      mozharness: 'public/build/mozharness.zip'
      test_packages: 'public/build/test_packages.json'
